server:
  port: 80

#Eureka配置
eureka:
  client:
   register-with-eureka: false #不向Eureka中注册自己
   service-url:
     defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://localhost:7003/eureka/

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
SPRINGCLOUD-PROVIDER-DEPT:
  ribbon:
#    NFLoadBalancerRuleClassName: com.joke.loadbalancer.MyRandomRule  #自定义负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

feign:
  hystrix:
    enabled: true # 开启服务降级